# Generated by Django 5.2.15 on 2026-07-19 08:25

import django.core.validators
import tasks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[tasks.validators.validate_deadline_not_in_past], verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[tasks.validators.validate_title_only_whitespace, django.core.validators.MinLengthValidator(3)], verbose_name='Заголовок'),
        ),
    ]
